version: '3'
services:
  flask:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/code
      - ./db:/db
    command: flask run --host=0.0.0.0
    environment:
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - CHIME_API_KEY=${CHIME_API_KEY}
      - CHIME_API_SECRET=${CHIME_API_SECRET}
