"""Add attendee index

Revision ID: 378fa8da1d0b
Revises: cacc3bc5dd47
Create Date: 2020-04-04 22:57:35.482375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378fa8da1d0b'
down_revision = 'cacc3bc5dd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendee_index'), 'attendee', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendee_index'), table_name='attendee')
    op.drop_column('attendee', 'index')
    # ### end Alembic commands ###
