"""Add attendee details

Revision ID: cacc3bc5dd47
Revises: f1345f4f028c
Create Date: 2020-04-04 22:56:17.196514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacc3bc5dd47'
down_revision = 'f1345f4f028c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('attendee_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee', 'attendee_details')
    # ### end Alembic commands ###
