"""Initial migration.

Revision ID: f1345f4f028c
Revises: 
Create Date: 2020-04-04 22:35:05.191712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1345f4f028c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('meeting_id', sa.String(length=50), nullable=True),
    sa.Column('meeting_details', sa.Text(), nullable=True),
    sa.Column('game_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_meeting_id'), 'game', ['meeting_id'], unique=True)
    op.create_index(op.f('ix_game_token'), 'game', ['token'], unique=True)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_token'), 'room', ['token'], unique=True)
    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendee_token'), 'attendee', ['token'], unique=True)
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_token'), 'participant', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participant_token'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_attendee_token'), table_name='attendee')
    op.drop_table('attendee')
    op.drop_index(op.f('ix_room_token'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_game_token'), table_name='game')
    op.drop_index(op.f('ix_game_meeting_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
